apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: kube-public
  labels:
    app: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: http
      port: 30021
      targetPort: 80
    - name: dashboard
      port: 30042
      targetPort: 8080
